# Generated by Django 5.0.3 on 2024-03-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo electrónico')),
                ('email_alternativo', models.EmailField(max_length=255, null=True, unique=True, verbose_name='Correo electrónico alternativo')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=10, unique=True, verbose_name='Documento')),
                ('telefono', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion_particular', models.CharField(max_length=255)),
                ('sexo', models.CharField(blank=True, max_length=2, null=True)),
                ('cedula_duplicada', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edad', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
