# Generated by Django 4.2.1 on 2023-09-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_pais_rename_name_user_nombre_user_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='documento',
            field=models.CharField(max_length=11, unique=True, verbose_name='Documento'),
        ),
    ]
