# Generated by Django 4.2.1 on 2023-09-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='documento',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='Documento'),
        ),
    ]
