# Generated by Django 4.2.1 on 2023-10-01 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='barrio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.barrio', verbose_name='Barrio'),
        ),
    ]
